---
version: "2.1"
services:
  db:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      - '3306:3306'
    volumes:
      - /mnt/shared/datastorage/nextcloud/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass nextcloud
    volumes:
      - /mnt/shared/datastorage/nextcloud/redisdata:/data

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:23.0.4-php8
    container_name: nextcloud
    volumes:
      - /mnt/shared/datastorage/nextcloud/appdata:/config
      - /mnt/backupstorage/nextcloud/data:/data
    ports:
      - 443:443
    links:
      - db
      - redis
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - NEXTCLOUD_ADMIN_USER=disco
      - NEXTCLOUD_ADMIN_PASSWORD=disco
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=20G
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=nextcloud
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS='"192.168.0.* 99.229.12.38 0.0.0.0""
    restart: unless-stopped
